// Copyright (c) ZeroC, Inc.

// slice2cpp version 3.8.2
// <auto-generated>Generated from Slice file 'JSONBINRPCU.ice'.</auto-generated>

#define ICE_BUILDING_GENERATED_CODE

#include "JSONBINRPCU.h"
#include <Ice/AsyncResponseHandler.h>
#include <Ice/DefaultSliceLoader.h>
#include <Ice/OutgoingAsync.h>
#include <algorithm>
#include <array>

#if defined(_MSC_VER)
#   pragma warning(disable : 4458) // declaration of ... hides class member
#   pragma warning(disable : 4996) // ... was declared deprecated
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#   pragma clang diagnostic ignored "-Wdeprecated-declarations"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#   pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#endif

#ifndef ICE_DISABLE_VERSION
#   if ICE_INT_VERSION / 100 != 308
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

JSONBINRPC::IJsonBinRPCPrx::~IJsonBinRPCPrx() = default;

std::int64_t
JSONBINRPC::IJsonBinRPCPrx::RegisterStockPushIO(std::string_view iceP_guid, const ::Ice::Identity& iceP_ident, const Ice::Context& context) const
{
    return IceInternal::makePromiseOutgoing<std::int64_t>(true, this, &IJsonBinRPCPrx::_iceI_RegisterStockPushIO, iceP_guid, iceP_ident, context).get();
}

std::future<std::int64_t>
JSONBINRPC::IJsonBinRPCPrx::RegisterStockPushIOAsync(std::string_view iceP_guid, const ::Ice::Identity& iceP_ident, const Ice::Context& context) const
{
    return IceInternal::makePromiseOutgoing<std::int64_t>(false, this, &IJsonBinRPCPrx::_iceI_RegisterStockPushIO, iceP_guid, iceP_ident, context);
}

std::function<void()>
JSONBINRPC::IJsonBinRPCPrx::RegisterStockPushIOAsync(std::string_view iceP_guid, const ::Ice::Identity& iceP_ident, std::function<void(std::int64_t)> response, std::function<void(std::exception_ptr)> exception, std::function<void(bool)> sent, const Ice::Context& context) const
{
    return IceInternal::makeLambdaOutgoing<std::int64_t>(std::move(response), std::move(exception), std::move(sent), this, &JSONBINRPC::IJsonBinRPCPrx::_iceI_RegisterStockPushIO, iceP_guid, iceP_ident, context);
}

void
JSONBINRPC::IJsonBinRPCPrx::_iceI_RegisterStockPushIO(const std::shared_ptr<IceInternal::OutgoingAsyncT<std::int64_t>>& outAsync, std::string_view iceP_guid, const ::Ice::Identity& iceP_ident, const Ice::Context& context) const
{
    static constexpr std::string_view operationName = "RegisterStockPushIO";

    _checkTwowayOnly(operationName);
    outAsync->invoke(
        operationName,
        Ice::OperationMode::Normal,
        std::nullopt,
        context,
        [&](Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_guid, iceP_ident);
        },
        nullptr);
}

std::int64_t
JSONBINRPC::IJsonBinRPCPrx::JsonBinRPC(std::int64_t iceP_syn, std::int64_t iceP_nFuncID, std::int64_t iceP_setcode, const AByte& iceP_reqJson, std::int64_t& iceP_ilparam, AByte& iceP_slparam, std::int64_t& iceP_iwparam, AByte& iceP_swparam, std::string& iceP_errinf, const Ice::Context& context) const
{
    auto result = IceInternal::makePromiseOutgoing<std::tuple<std::int64_t, std::int64_t, AByte, std::int64_t, AByte, std::string>>(true, this, &IJsonBinRPCPrx::_iceI_JsonBinRPC, iceP_syn, iceP_nFuncID, iceP_setcode, iceP_reqJson, context).get();
    iceP_ilparam = std::get<1>(result);
    iceP_slparam = std::move(std::get<2>(result));
    iceP_iwparam = std::get<3>(result);
    iceP_swparam = std::move(std::get<4>(result));
    iceP_errinf = std::move(std::get<5>(result));
    return std::get<0>(result);
}

std::future<std::tuple<std::int64_t, std::int64_t, ::JSONBINRPC::AByte, std::int64_t, ::JSONBINRPC::AByte, std::string>>
JSONBINRPC::IJsonBinRPCPrx::JsonBinRPCAsync(std::int64_t iceP_syn, std::int64_t iceP_nFuncID, std::int64_t iceP_setcode, const AByte& iceP_reqJson, const Ice::Context& context) const
{
    return IceInternal::makePromiseOutgoing<std::tuple<std::int64_t, std::int64_t, AByte, std::int64_t, AByte, std::string>>(false, this, &IJsonBinRPCPrx::_iceI_JsonBinRPC, iceP_syn, iceP_nFuncID, iceP_setcode, iceP_reqJson, context);
}

std::function<void()>
JSONBINRPC::IJsonBinRPCPrx::JsonBinRPCAsync(std::int64_t iceP_syn, std::int64_t iceP_nFuncID, std::int64_t iceP_setcode, const AByte& iceP_reqJson, std::function<void(std::int64_t, std::int64_t, ::JSONBINRPC::AByte, std::int64_t, ::JSONBINRPC::AByte, std::string)> response, std::function<void(std::exception_ptr)> exception, std::function<void(bool)> sent, const Ice::Context& context) const
{
    auto responseCb = [response = std::move(response)](std::tuple<std::int64_t, std::int64_t, AByte, std::int64_t, AByte, std::string>&& result) mutable
    {
        std::apply(std::move(response), std::move(result));
    };
    return IceInternal::makeLambdaOutgoing<std::tuple<std::int64_t, std::int64_t, AByte, std::int64_t, AByte, std::string>>(std::move(responseCb), std::move(exception), std::move(sent), this, &JSONBINRPC::IJsonBinRPCPrx::_iceI_JsonBinRPC, iceP_syn, iceP_nFuncID, iceP_setcode, iceP_reqJson, context);
}

void
JSONBINRPC::IJsonBinRPCPrx::_iceI_JsonBinRPC(const std::shared_ptr<IceInternal::OutgoingAsyncT<std::tuple<std::int64_t, std::int64_t, AByte, std::int64_t, AByte, std::string>>>& outAsync, std::int64_t iceP_syn, std::int64_t iceP_nFuncID, std::int64_t iceP_setcode, const AByte& iceP_reqJson, const Ice::Context& context) const
{
    static constexpr std::string_view operationName = "JsonBinRPC";

    _checkTwowayOnly(operationName);
    outAsync->invoke(
        operationName,
        Ice::OperationMode::Normal,
        std::nullopt,
        context,
        [&](Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_syn, iceP_nFuncID, iceP_setcode, iceP_reqJson);
        },
        nullptr,
        [](Ice::InputStream* istr)
        {
            std::tuple<std::int64_t, std::int64_t, AByte, std::int64_t, AByte, std::string> v;
            istr->readAll(std::get<1>(v), std::get<2>(v), std::get<3>(v), std::get<4>(v), std::get<5>(v), std::get<0>(v));
            return v;
        });
}

std::int64_t
JSONBINRPC::IJsonBinRPCPrx::JsonBinPUT(std::int64_t iceP_syn, std::int64_t iceP_nFuncID, std::int64_t iceP_setcode, const AByte& iceP_putJson, std::int64_t iceP_ilparam, const AByte& iceP_slparam, std::int64_t iceP_iwparam, const AByte& iceP_swparam, std::int64_t& iceP_oilparam, AByte& iceP_oslparam, std::int64_t& iceP_oiwparam, AByte& iceP_oswparam, std::string& iceP_errinf, const Ice::Context& context) const
{
    auto result = IceInternal::makePromiseOutgoing<std::tuple<std::int64_t, std::int64_t, AByte, std::int64_t, AByte, std::string>>(true, this, &IJsonBinRPCPrx::_iceI_JsonBinPUT, iceP_syn, iceP_nFuncID, iceP_setcode, iceP_putJson, iceP_ilparam, iceP_slparam, iceP_iwparam, iceP_swparam, context).get();
    iceP_oilparam = std::get<1>(result);
    iceP_oslparam = std::move(std::get<2>(result));
    iceP_oiwparam = std::get<3>(result);
    iceP_oswparam = std::move(std::get<4>(result));
    iceP_errinf = std::move(std::get<5>(result));
    return std::get<0>(result);
}

std::future<std::tuple<std::int64_t, std::int64_t, ::JSONBINRPC::AByte, std::int64_t, ::JSONBINRPC::AByte, std::string>>
JSONBINRPC::IJsonBinRPCPrx::JsonBinPUTAsync(std::int64_t iceP_syn, std::int64_t iceP_nFuncID, std::int64_t iceP_setcode, const AByte& iceP_putJson, std::int64_t iceP_ilparam, const AByte& iceP_slparam, std::int64_t iceP_iwparam, const AByte& iceP_swparam, const Ice::Context& context) const
{
    return IceInternal::makePromiseOutgoing<std::tuple<std::int64_t, std::int64_t, AByte, std::int64_t, AByte, std::string>>(false, this, &IJsonBinRPCPrx::_iceI_JsonBinPUT, iceP_syn, iceP_nFuncID, iceP_setcode, iceP_putJson, iceP_ilparam, iceP_slparam, iceP_iwparam, iceP_swparam, context);
}

std::function<void()>
JSONBINRPC::IJsonBinRPCPrx::JsonBinPUTAsync(std::int64_t iceP_syn, std::int64_t iceP_nFuncID, std::int64_t iceP_setcode, const AByte& iceP_putJson, std::int64_t iceP_ilparam, const AByte& iceP_slparam, std::int64_t iceP_iwparam, const AByte& iceP_swparam, std::function<void(std::int64_t, std::int64_t, ::JSONBINRPC::AByte, std::int64_t, ::JSONBINRPC::AByte, std::string)> response, std::function<void(std::exception_ptr)> exception, std::function<void(bool)> sent, const Ice::Context& context) const
{
    auto responseCb = [response = std::move(response)](std::tuple<std::int64_t, std::int64_t, AByte, std::int64_t, AByte, std::string>&& result) mutable
    {
        std::apply(std::move(response), std::move(result));
    };
    return IceInternal::makeLambdaOutgoing<std::tuple<std::int64_t, std::int64_t, AByte, std::int64_t, AByte, std::string>>(std::move(responseCb), std::move(exception), std::move(sent), this, &JSONBINRPC::IJsonBinRPCPrx::_iceI_JsonBinPUT, iceP_syn, iceP_nFuncID, iceP_setcode, iceP_putJson, iceP_ilparam, iceP_slparam, iceP_iwparam, iceP_swparam, context);
}

void
JSONBINRPC::IJsonBinRPCPrx::_iceI_JsonBinPUT(const std::shared_ptr<IceInternal::OutgoingAsyncT<std::tuple<std::int64_t, std::int64_t, AByte, std::int64_t, AByte, std::string>>>& outAsync, std::int64_t iceP_syn, std::int64_t iceP_nFuncID, std::int64_t iceP_setcode, const AByte& iceP_putJson, std::int64_t iceP_ilparam, const AByte& iceP_slparam, std::int64_t iceP_iwparam, const AByte& iceP_swparam, const Ice::Context& context) const
{
    static constexpr std::string_view operationName = "JsonBinPUT";

    _checkTwowayOnly(operationName);
    outAsync->invoke(
        operationName,
        Ice::OperationMode::Normal,
        std::nullopt,
        context,
        [&](Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_syn, iceP_nFuncID, iceP_setcode, iceP_putJson, iceP_ilparam, iceP_slparam, iceP_iwparam, iceP_swparam);
        },
        nullptr,
        [](Ice::InputStream* istr)
        {
            std::tuple<std::int64_t, std::int64_t, AByte, std::int64_t, AByte, std::string> v;
            istr->readAll(std::get<1>(v), std::get<2>(v), std::get<3>(v), std::get<4>(v), std::get<5>(v), std::get<0>(v));
            return v;
        });
}

std::int64_t
JSONBINRPC::IJsonBinRPCPrx::UnRegisterStockPushIO(std::string_view iceP_guid, const Ice::Context& context) const
{
    return IceInternal::makePromiseOutgoing<std::int64_t>(true, this, &IJsonBinRPCPrx::_iceI_UnRegisterStockPushIO, iceP_guid, context).get();
}

std::future<std::int64_t>
JSONBINRPC::IJsonBinRPCPrx::UnRegisterStockPushIOAsync(std::string_view iceP_guid, const Ice::Context& context) const
{
    return IceInternal::makePromiseOutgoing<std::int64_t>(false, this, &IJsonBinRPCPrx::_iceI_UnRegisterStockPushIO, iceP_guid, context);
}

std::function<void()>
JSONBINRPC::IJsonBinRPCPrx::UnRegisterStockPushIOAsync(std::string_view iceP_guid, std::function<void(std::int64_t)> response, std::function<void(std::exception_ptr)> exception, std::function<void(bool)> sent, const Ice::Context& context) const
{
    return IceInternal::makeLambdaOutgoing<std::int64_t>(std::move(response), std::move(exception), std::move(sent), this, &JSONBINRPC::IJsonBinRPCPrx::_iceI_UnRegisterStockPushIO, iceP_guid, context);
}

void
JSONBINRPC::IJsonBinRPCPrx::_iceI_UnRegisterStockPushIO(const std::shared_ptr<IceInternal::OutgoingAsyncT<std::int64_t>>& outAsync, std::string_view iceP_guid, const Ice::Context& context) const
{
    static constexpr std::string_view operationName = "UnRegisterStockPushIO";

    _checkTwowayOnly(operationName);
    outAsync->invoke(
        operationName,
        Ice::OperationMode::Normal,
        std::nullopt,
        context,
        [&](Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_guid);
        },
        nullptr);
}

void
JSONBINRPC::IJsonBinRPCPrx::ProcessPackage(std::int64_t iceP_reqno, const AByte& iceP_buf, const Ice::Context& context) const
{
    IceInternal::makePromiseOutgoing<void>(true, this, &IJsonBinRPCPrx::_iceI_ProcessPackage, iceP_reqno, iceP_buf, context).get();
}

std::future<void>
JSONBINRPC::IJsonBinRPCPrx::ProcessPackageAsync(std::int64_t iceP_reqno, const AByte& iceP_buf, const Ice::Context& context) const
{
    return IceInternal::makePromiseOutgoing<void>(false, this, &IJsonBinRPCPrx::_iceI_ProcessPackage, iceP_reqno, iceP_buf, context);
}

std::function<void()>
JSONBINRPC::IJsonBinRPCPrx::ProcessPackageAsync(std::int64_t iceP_reqno, const AByte& iceP_buf, std::function<void()> response, std::function<void(std::exception_ptr)> exception, std::function<void(bool)> sent, const Ice::Context& context) const
{
    return IceInternal::makeLambdaOutgoing<void>(std::move(response), std::move(exception), std::move(sent), this, &JSONBINRPC::IJsonBinRPCPrx::_iceI_ProcessPackage, iceP_reqno, iceP_buf, context);
}

void
JSONBINRPC::IJsonBinRPCPrx::_iceI_ProcessPackage(const std::shared_ptr<IceInternal::OutgoingAsyncT<void>>& outAsync, std::int64_t iceP_reqno, const AByte& iceP_buf, const Ice::Context& context) const
{
    static constexpr std::string_view operationName = "ProcessPackage";

    outAsync->invoke(
        operationName,
        Ice::OperationMode::Normal,
        std::nullopt,
        context,
        [&](Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_reqno, iceP_buf);
        },
        nullptr);
}

std::string
JSONBINRPC::IJsonBinRPCPrx::RegisterStockPushIO2(std::string_view iceP_guid, std::string_view iceP_subinfo, const ::Ice::Identity& iceP_ident, const Ice::Context& context) const
{
    return IceInternal::makePromiseOutgoing<std::string>(true, this, &IJsonBinRPCPrx::_iceI_RegisterStockPushIO2, iceP_guid, iceP_subinfo, iceP_ident, context).get();
}

std::future<std::string>
JSONBINRPC::IJsonBinRPCPrx::RegisterStockPushIO2Async(std::string_view iceP_guid, std::string_view iceP_subinfo, const ::Ice::Identity& iceP_ident, const Ice::Context& context) const
{
    return IceInternal::makePromiseOutgoing<std::string>(false, this, &IJsonBinRPCPrx::_iceI_RegisterStockPushIO2, iceP_guid, iceP_subinfo, iceP_ident, context);
}

std::function<void()>
JSONBINRPC::IJsonBinRPCPrx::RegisterStockPushIO2Async(std::string_view iceP_guid, std::string_view iceP_subinfo, const ::Ice::Identity& iceP_ident, std::function<void(std::string)> response, std::function<void(std::exception_ptr)> exception, std::function<void(bool)> sent, const Ice::Context& context) const
{
    return IceInternal::makeLambdaOutgoing<std::string>(std::move(response), std::move(exception), std::move(sent), this, &JSONBINRPC::IJsonBinRPCPrx::_iceI_RegisterStockPushIO2, iceP_guid, iceP_subinfo, iceP_ident, context);
}

void
JSONBINRPC::IJsonBinRPCPrx::_iceI_RegisterStockPushIO2(const std::shared_ptr<IceInternal::OutgoingAsyncT<std::string>>& outAsync, std::string_view iceP_guid, std::string_view iceP_subinfo, const ::Ice::Identity& iceP_ident, const Ice::Context& context) const
{
    static constexpr std::string_view operationName = "RegisterStockPushIO2";

    _checkTwowayOnly(operationName);
    outAsync->invoke(
        operationName,
        Ice::OperationMode::Normal,
        std::nullopt,
        context,
        [&](Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_guid, iceP_subinfo, iceP_ident);
        },
        nullptr);
}

std::string
JSONBINRPC::IJsonBinRPCPrx::UnRegisterStockPushIO2(std::string_view iceP_guid, std::string_view iceP_subinfo, const ::Ice::Identity& iceP_ident, const Ice::Context& context) const
{
    return IceInternal::makePromiseOutgoing<std::string>(true, this, &IJsonBinRPCPrx::_iceI_UnRegisterStockPushIO2, iceP_guid, iceP_subinfo, iceP_ident, context).get();
}

std::future<std::string>
JSONBINRPC::IJsonBinRPCPrx::UnRegisterStockPushIO2Async(std::string_view iceP_guid, std::string_view iceP_subinfo, const ::Ice::Identity& iceP_ident, const Ice::Context& context) const
{
    return IceInternal::makePromiseOutgoing<std::string>(false, this, &IJsonBinRPCPrx::_iceI_UnRegisterStockPushIO2, iceP_guid, iceP_subinfo, iceP_ident, context);
}

std::function<void()>
JSONBINRPC::IJsonBinRPCPrx::UnRegisterStockPushIO2Async(std::string_view iceP_guid, std::string_view iceP_subinfo, const ::Ice::Identity& iceP_ident, std::function<void(std::string)> response, std::function<void(std::exception_ptr)> exception, std::function<void(bool)> sent, const Ice::Context& context) const
{
    return IceInternal::makeLambdaOutgoing<std::string>(std::move(response), std::move(exception), std::move(sent), this, &JSONBINRPC::IJsonBinRPCPrx::_iceI_UnRegisterStockPushIO2, iceP_guid, iceP_subinfo, iceP_ident, context);
}

void
JSONBINRPC::IJsonBinRPCPrx::_iceI_UnRegisterStockPushIO2(const std::shared_ptr<IceInternal::OutgoingAsyncT<std::string>>& outAsync, std::string_view iceP_guid, std::string_view iceP_subinfo, const ::Ice::Identity& iceP_ident, const Ice::Context& context) const
{
    static constexpr std::string_view operationName = "UnRegisterStockPushIO2";

    _checkTwowayOnly(operationName);
    outAsync->invoke(
        operationName,
        Ice::OperationMode::Normal,
        std::nullopt,
        context,
        [&](Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_guid, iceP_subinfo, iceP_ident);
        },
        nullptr);
}

const char*
JSONBINRPC::IJsonBinRPCPrx::ice_staticId() noexcept
{
    return "::JSONBINRPC::IJsonBinRPC";
}

void
JSONBINRPC::IJsonBinRPC::dispatch(Ice::IncomingRequest& request, std::function<void(Ice::OutgoingResponse)> sendResponse)
{
    static constexpr std::array<std::string_view, 11> allOperations{"JsonBinPUT", "JsonBinRPC", "ProcessPackage", "RegisterStockPushIO", "RegisterStockPushIO2", "UnRegisterStockPushIO", "UnRegisterStockPushIO2", "ice_id", "ice_ids", "ice_isA", "ice_ping"};

    const Ice::Current& current = request.current();
    auto r = std::equal_range(allOperations.begin(), allOperations.end(), current.operation); // NOLINT(modernize-use-ranges)
    if (r.first == r.second)
    {
        sendResponse(Ice::makeOutgoingResponse(std::make_exception_ptr(Ice::OperationNotExistException{__FILE__, __LINE__}), current));
        return;
    }

    switch (r.first - allOperations.begin())
    {
        case 0:
        {
            _iceD_JsonBinPUT(request, std::move(sendResponse));
            break;
        }
        case 1:
        {
            _iceD_JsonBinRPC(request, std::move(sendResponse));
            break;
        }
        case 2:
        {
            _iceD_ProcessPackage(request, std::move(sendResponse));
            break;
        }
        case 3:
        {
            _iceD_RegisterStockPushIO(request, std::move(sendResponse));
            break;
        }
        case 4:
        {
            _iceD_RegisterStockPushIO2(request, std::move(sendResponse));
            break;
        }
        case 5:
        {
            _iceD_UnRegisterStockPushIO(request, std::move(sendResponse));
            break;
        }
        case 6:
        {
            _iceD_UnRegisterStockPushIO2(request, std::move(sendResponse));
            break;
        }
        case 7:
        {
            _iceD_ice_id(request, std::move(sendResponse));
            break;
        }
        case 8:
        {
            _iceD_ice_ids(request, std::move(sendResponse));
            break;
        }
        case 9:
        {
            _iceD_ice_isA(request, std::move(sendResponse));
            break;
        }
        case 10:
        {
            _iceD_ice_ping(request, std::move(sendResponse));
            break;
        }
        default:
        {
            assert(false);
            sendResponse(Ice::makeOutgoingResponse(std::make_exception_ptr(Ice::OperationNotExistException{__FILE__, __LINE__}), current));
        }
    }
}

std::vector<std::string>
JSONBINRPC::IJsonBinRPC::ice_ids(const Ice::Current&) const
{
    static const std::vector<std::string> allTypeIds = {"::Ice::Object", "::JSONBINRPC::IJsonBinRPC"};
    return allTypeIds;
}

std::string
JSONBINRPC::IJsonBinRPC::ice_id(const Ice::Current&) const
{
    return std::string{ice_staticId()};
}

void
JSONBINRPC::IJsonBinRPC::_iceD_RegisterStockPushIO(
    Ice::IncomingRequest& request,
    std::function<void(Ice::OutgoingResponse)> sendResponse)
{
    checkNonIdempotent(request.current());
    auto istr = &request.inputStream();
    istr->startEncapsulation();
    std::string iceP_guid;
    ::Ice::Identity iceP_ident;
    istr->readAll(iceP_guid, iceP_ident);
    istr->endEncapsulation();
    auto responseHandler = std::make_shared<IceInternal::AsyncResponseHandler>(std::move(sendResponse), request.current());
    auto responseCb = [responseHandler](std::int64_t ret)
    {
        responseHandler->sendResponse(
            [&](Ice::OutputStream* ostr)
            {
                ostr->writeAll(ret);
            });
    };
    try
    {
        this->RegisterStockPushIOAsync(std::move(iceP_guid), std::move(iceP_ident), std::move(responseCb), [responseHandler](std::exception_ptr ex) { responseHandler->sendException(ex); }, responseHandler->current());
    }
    catch (...)
    {
        responseHandler->sendException(std::current_exception());
    }
}

void
JSONBINRPC::IJsonBinRPC::_iceD_JsonBinRPC(
    Ice::IncomingRequest& request,
    std::function<void(Ice::OutgoingResponse)> sendResponse)
{
    checkNonIdempotent(request.current());
    auto istr = &request.inputStream();
    istr->startEncapsulation();
    std::int64_t iceP_syn;
    std::int64_t iceP_nFuncID;
    std::int64_t iceP_setcode;
    AByte iceP_reqJson;
    istr->readAll(iceP_syn, iceP_nFuncID, iceP_setcode, iceP_reqJson);
    istr->endEncapsulation();
    auto responseHandler = std::make_shared<IceInternal::AsyncResponseHandler>(std::move(sendResponse), request.current());
    auto responseCb = [responseHandler](std::int64_t ret, std::int64_t iceP_ilparam, const AByte& iceP_slparam, std::int64_t iceP_iwparam, const AByte& iceP_swparam, std::string_view iceP_errinf)
    {
        responseHandler->sendResponse(
            [&](Ice::OutputStream* ostr)
            {
                ostr->writeAll(iceP_ilparam, iceP_slparam, iceP_iwparam, iceP_swparam, iceP_errinf, ret);
            });
    };
    try
    {
        this->JsonBinRPCAsync(iceP_syn, iceP_nFuncID, iceP_setcode, std::move(iceP_reqJson), std::move(responseCb), [responseHandler](std::exception_ptr ex) { responseHandler->sendException(ex); }, responseHandler->current());
    }
    catch (...)
    {
        responseHandler->sendException(std::current_exception());
    }
}

void
JSONBINRPC::IJsonBinRPC::_iceD_JsonBinPUT(
    Ice::IncomingRequest& request,
    std::function<void(Ice::OutgoingResponse)> sendResponse)
{
    checkNonIdempotent(request.current());
    auto istr = &request.inputStream();
    istr->startEncapsulation();
    std::int64_t iceP_syn;
    std::int64_t iceP_nFuncID;
    std::int64_t iceP_setcode;
    AByte iceP_putJson;
    std::int64_t iceP_ilparam;
    AByte iceP_slparam;
    std::int64_t iceP_iwparam;
    AByte iceP_swparam;
    istr->readAll(iceP_syn, iceP_nFuncID, iceP_setcode, iceP_putJson, iceP_ilparam, iceP_slparam, iceP_iwparam, iceP_swparam);
    istr->endEncapsulation();
    auto responseHandler = std::make_shared<IceInternal::AsyncResponseHandler>(std::move(sendResponse), request.current());
    auto responseCb = [responseHandler](std::int64_t ret, std::int64_t iceP_oilparam, const AByte& iceP_oslparam, std::int64_t iceP_oiwparam, const AByte& iceP_oswparam, std::string_view iceP_errinf)
    {
        responseHandler->sendResponse(
            [&](Ice::OutputStream* ostr)
            {
                ostr->writeAll(iceP_oilparam, iceP_oslparam, iceP_oiwparam, iceP_oswparam, iceP_errinf, ret);
            });
    };
    try
    {
        this->JsonBinPUTAsync(iceP_syn, iceP_nFuncID, iceP_setcode, std::move(iceP_putJson), iceP_ilparam, std::move(iceP_slparam), iceP_iwparam, std::move(iceP_swparam), std::move(responseCb), [responseHandler](std::exception_ptr ex) { responseHandler->sendException(ex); }, responseHandler->current());
    }
    catch (...)
    {
        responseHandler->sendException(std::current_exception());
    }
}

void
JSONBINRPC::IJsonBinRPC::_iceD_UnRegisterStockPushIO(
    Ice::IncomingRequest& request,
    std::function<void(Ice::OutgoingResponse)> sendResponse)
{
    checkNonIdempotent(request.current());
    auto istr = &request.inputStream();
    istr->startEncapsulation();
    std::string iceP_guid;
    istr->readAll(iceP_guid);
    istr->endEncapsulation();
    auto responseHandler = std::make_shared<IceInternal::AsyncResponseHandler>(std::move(sendResponse), request.current());
    auto responseCb = [responseHandler](std::int64_t ret)
    {
        responseHandler->sendResponse(
            [&](Ice::OutputStream* ostr)
            {
                ostr->writeAll(ret);
            });
    };
    try
    {
        this->UnRegisterStockPushIOAsync(std::move(iceP_guid), std::move(responseCb), [responseHandler](std::exception_ptr ex) { responseHandler->sendException(ex); }, responseHandler->current());
    }
    catch (...)
    {
        responseHandler->sendException(std::current_exception());
    }
}

void
JSONBINRPC::IJsonBinRPC::_iceD_ProcessPackage(
    Ice::IncomingRequest& request,
    std::function<void(Ice::OutgoingResponse)> sendResponse)
{
    checkNonIdempotent(request.current());
    auto istr = &request.inputStream();
    istr->startEncapsulation();
    std::int64_t iceP_reqno;
    AByte iceP_buf;
    istr->readAll(iceP_reqno, iceP_buf);
    istr->endEncapsulation();
    auto responseHandler = std::make_shared<IceInternal::AsyncResponseHandler>(std::move(sendResponse), request.current());
    try
    {
        this->ProcessPackageAsync(iceP_reqno, std::move(iceP_buf), [responseHandler] { responseHandler->sendEmptyResponse(); }, [responseHandler](std::exception_ptr ex) { responseHandler->sendException(ex); }, responseHandler->current());
    }
    catch (...)
    {
        responseHandler->sendException(std::current_exception());
    }
}

void
JSONBINRPC::IJsonBinRPC::_iceD_RegisterStockPushIO2(
    Ice::IncomingRequest& request,
    std::function<void(Ice::OutgoingResponse)> sendResponse)
{
    checkNonIdempotent(request.current());
    auto istr = &request.inputStream();
    istr->startEncapsulation();
    std::string iceP_guid;
    std::string iceP_subinfo;
    ::Ice::Identity iceP_ident;
    istr->readAll(iceP_guid, iceP_subinfo, iceP_ident);
    istr->endEncapsulation();
    auto responseHandler = std::make_shared<IceInternal::AsyncResponseHandler>(std::move(sendResponse), request.current());
    auto responseCb = [responseHandler](std::string_view ret)
    {
        responseHandler->sendResponse(
            [&](Ice::OutputStream* ostr)
            {
                ostr->writeAll(ret);
            });
    };
    try
    {
        this->RegisterStockPushIO2Async(std::move(iceP_guid), std::move(iceP_subinfo), std::move(iceP_ident), std::move(responseCb), [responseHandler](std::exception_ptr ex) { responseHandler->sendException(ex); }, responseHandler->current());
    }
    catch (...)
    {
        responseHandler->sendException(std::current_exception());
    }
}

void
JSONBINRPC::IJsonBinRPC::_iceD_UnRegisterStockPushIO2(
    Ice::IncomingRequest& request,
    std::function<void(Ice::OutgoingResponse)> sendResponse)
{
    checkNonIdempotent(request.current());
    auto istr = &request.inputStream();
    istr->startEncapsulation();
    std::string iceP_guid;
    std::string iceP_subinfo;
    ::Ice::Identity iceP_ident;
    istr->readAll(iceP_guid, iceP_subinfo, iceP_ident);
    istr->endEncapsulation();
    auto responseHandler = std::make_shared<IceInternal::AsyncResponseHandler>(std::move(sendResponse), request.current());
    auto responseCb = [responseHandler](std::string_view ret)
    {
        responseHandler->sendResponse(
            [&](Ice::OutputStream* ostr)
            {
                ostr->writeAll(ret);
            });
    };
    try
    {
        this->UnRegisterStockPushIO2Async(std::move(iceP_guid), std::move(iceP_subinfo), std::move(iceP_ident), std::move(responseCb), [responseHandler](std::exception_ptr ex) { responseHandler->sendException(ex); }, responseHandler->current());
    }
    catch (...)
    {
        responseHandler->sendException(std::current_exception());
    }
}

const char*
JSONBINRPC::IJsonBinRPC::ice_staticId() noexcept
{
    return "::JSONBINRPC::IJsonBinRPC";
}

void
JSONBINRPC::AsyncIJsonBinRPC::dispatch(Ice::IncomingRequest& request, std::function<void(Ice::OutgoingResponse)> sendResponse)
{
    static constexpr std::array<std::string_view, 11> allOperations{"JsonBinPUT", "JsonBinRPC", "ProcessPackage", "RegisterStockPushIO", "RegisterStockPushIO2", "UnRegisterStockPushIO", "UnRegisterStockPushIO2", "ice_id", "ice_ids", "ice_isA", "ice_ping"};

    const Ice::Current& current = request.current();
    auto r = std::equal_range(allOperations.begin(), allOperations.end(), current.operation); // NOLINT(modernize-use-ranges)
    if (r.first == r.second)
    {
        sendResponse(Ice::makeOutgoingResponse(std::make_exception_ptr(Ice::OperationNotExistException{__FILE__, __LINE__}), current));
        return;
    }

    switch (r.first - allOperations.begin())
    {
        case 0:
        {
            _iceD_JsonBinPUT(request, std::move(sendResponse));
            break;
        }
        case 1:
        {
            _iceD_JsonBinRPC(request, std::move(sendResponse));
            break;
        }
        case 2:
        {
            _iceD_ProcessPackage(request, std::move(sendResponse));
            break;
        }
        case 3:
        {
            _iceD_RegisterStockPushIO(request, std::move(sendResponse));
            break;
        }
        case 4:
        {
            _iceD_RegisterStockPushIO2(request, std::move(sendResponse));
            break;
        }
        case 5:
        {
            _iceD_UnRegisterStockPushIO(request, std::move(sendResponse));
            break;
        }
        case 6:
        {
            _iceD_UnRegisterStockPushIO2(request, std::move(sendResponse));
            break;
        }
        case 7:
        {
            _iceD_ice_id(request, std::move(sendResponse));
            break;
        }
        case 8:
        {
            _iceD_ice_ids(request, std::move(sendResponse));
            break;
        }
        case 9:
        {
            _iceD_ice_isA(request, std::move(sendResponse));
            break;
        }
        case 10:
        {
            _iceD_ice_ping(request, std::move(sendResponse));
            break;
        }
        default:
        {
            assert(false);
            sendResponse(Ice::makeOutgoingResponse(std::make_exception_ptr(Ice::OperationNotExistException{__FILE__, __LINE__}), current));
        }
    }
}

std::vector<std::string>
JSONBINRPC::AsyncIJsonBinRPC::ice_ids(const Ice::Current&) const
{
    static const std::vector<std::string> allTypeIds = {"::Ice::Object", "::JSONBINRPC::IJsonBinRPC"};
    return allTypeIds;
}

std::string
JSONBINRPC::AsyncIJsonBinRPC::ice_id(const Ice::Current&) const
{
    return std::string{ice_staticId()};
}

void
JSONBINRPC::AsyncIJsonBinRPC::_iceD_RegisterStockPushIO(
    Ice::IncomingRequest& request,
    std::function<void(Ice::OutgoingResponse)> sendResponse)
{
    checkNonIdempotent(request.current());
    auto istr = &request.inputStream();
    istr->startEncapsulation();
    std::string iceP_guid;
    ::Ice::Identity iceP_ident;
    istr->readAll(iceP_guid, iceP_ident);
    istr->endEncapsulation();
    auto responseHandler = std::make_shared<IceInternal::AsyncResponseHandler>(std::move(sendResponse), request.current());
    auto responseCb = [responseHandler](std::int64_t ret)
    {
        responseHandler->sendResponse(
            [&](Ice::OutputStream* ostr)
            {
                ostr->writeAll(ret);
            });
    };
    try
    {
        this->RegisterStockPushIOAsync(std::move(iceP_guid), std::move(iceP_ident), std::move(responseCb), [responseHandler](std::exception_ptr ex) { responseHandler->sendException(ex); }, responseHandler->current());
    }
    catch (...)
    {
        responseHandler->sendException(std::current_exception());
    }
}

void
JSONBINRPC::AsyncIJsonBinRPC::_iceD_JsonBinRPC(
    Ice::IncomingRequest& request,
    std::function<void(Ice::OutgoingResponse)> sendResponse)
{
    checkNonIdempotent(request.current());
    auto istr = &request.inputStream();
    istr->startEncapsulation();
    std::int64_t iceP_syn;
    std::int64_t iceP_nFuncID;
    std::int64_t iceP_setcode;
    AByte iceP_reqJson;
    istr->readAll(iceP_syn, iceP_nFuncID, iceP_setcode, iceP_reqJson);
    istr->endEncapsulation();
    auto responseHandler = std::make_shared<IceInternal::AsyncResponseHandler>(std::move(sendResponse), request.current());
    auto responseCb = [responseHandler](std::int64_t ret, std::int64_t iceP_ilparam, const AByte& iceP_slparam, std::int64_t iceP_iwparam, const AByte& iceP_swparam, std::string_view iceP_errinf)
    {
        responseHandler->sendResponse(
            [&](Ice::OutputStream* ostr)
            {
                ostr->writeAll(iceP_ilparam, iceP_slparam, iceP_iwparam, iceP_swparam, iceP_errinf, ret);
            });
    };
    try
    {
        this->JsonBinRPCAsync(iceP_syn, iceP_nFuncID, iceP_setcode, std::move(iceP_reqJson), std::move(responseCb), [responseHandler](std::exception_ptr ex) { responseHandler->sendException(ex); }, responseHandler->current());
    }
    catch (...)
    {
        responseHandler->sendException(std::current_exception());
    }
}

void
JSONBINRPC::AsyncIJsonBinRPC::_iceD_JsonBinPUT(
    Ice::IncomingRequest& request,
    std::function<void(Ice::OutgoingResponse)> sendResponse)
{
    checkNonIdempotent(request.current());
    auto istr = &request.inputStream();
    istr->startEncapsulation();
    std::int64_t iceP_syn;
    std::int64_t iceP_nFuncID;
    std::int64_t iceP_setcode;
    AByte iceP_putJson;
    std::int64_t iceP_ilparam;
    AByte iceP_slparam;
    std::int64_t iceP_iwparam;
    AByte iceP_swparam;
    istr->readAll(iceP_syn, iceP_nFuncID, iceP_setcode, iceP_putJson, iceP_ilparam, iceP_slparam, iceP_iwparam, iceP_swparam);
    istr->endEncapsulation();
    auto responseHandler = std::make_shared<IceInternal::AsyncResponseHandler>(std::move(sendResponse), request.current());
    auto responseCb = [responseHandler](std::int64_t ret, std::int64_t iceP_oilparam, const AByte& iceP_oslparam, std::int64_t iceP_oiwparam, const AByte& iceP_oswparam, std::string_view iceP_errinf)
    {
        responseHandler->sendResponse(
            [&](Ice::OutputStream* ostr)
            {
                ostr->writeAll(iceP_oilparam, iceP_oslparam, iceP_oiwparam, iceP_oswparam, iceP_errinf, ret);
            });
    };
    try
    {
        this->JsonBinPUTAsync(iceP_syn, iceP_nFuncID, iceP_setcode, std::move(iceP_putJson), iceP_ilparam, std::move(iceP_slparam), iceP_iwparam, std::move(iceP_swparam), std::move(responseCb), [responseHandler](std::exception_ptr ex) { responseHandler->sendException(ex); }, responseHandler->current());
    }
    catch (...)
    {
        responseHandler->sendException(std::current_exception());
    }
}

void
JSONBINRPC::AsyncIJsonBinRPC::_iceD_UnRegisterStockPushIO(
    Ice::IncomingRequest& request,
    std::function<void(Ice::OutgoingResponse)> sendResponse)
{
    checkNonIdempotent(request.current());
    auto istr = &request.inputStream();
    istr->startEncapsulation();
    std::string iceP_guid;
    istr->readAll(iceP_guid);
    istr->endEncapsulation();
    auto responseHandler = std::make_shared<IceInternal::AsyncResponseHandler>(std::move(sendResponse), request.current());
    auto responseCb = [responseHandler](std::int64_t ret)
    {
        responseHandler->sendResponse(
            [&](Ice::OutputStream* ostr)
            {
                ostr->writeAll(ret);
            });
    };
    try
    {
        this->UnRegisterStockPushIOAsync(std::move(iceP_guid), std::move(responseCb), [responseHandler](std::exception_ptr ex) { responseHandler->sendException(ex); }, responseHandler->current());
    }
    catch (...)
    {
        responseHandler->sendException(std::current_exception());
    }
}

void
JSONBINRPC::AsyncIJsonBinRPC::_iceD_ProcessPackage(
    Ice::IncomingRequest& request,
    std::function<void(Ice::OutgoingResponse)> sendResponse)
{
    checkNonIdempotent(request.current());
    auto istr = &request.inputStream();
    istr->startEncapsulation();
    std::int64_t iceP_reqno;
    AByte iceP_buf;
    istr->readAll(iceP_reqno, iceP_buf);
    istr->endEncapsulation();
    auto responseHandler = std::make_shared<IceInternal::AsyncResponseHandler>(std::move(sendResponse), request.current());
    try
    {
        this->ProcessPackageAsync(iceP_reqno, std::move(iceP_buf), [responseHandler] { responseHandler->sendEmptyResponse(); }, [responseHandler](std::exception_ptr ex) { responseHandler->sendException(ex); }, responseHandler->current());
    }
    catch (...)
    {
        responseHandler->sendException(std::current_exception());
    }
}

void
JSONBINRPC::AsyncIJsonBinRPC::_iceD_RegisterStockPushIO2(
    Ice::IncomingRequest& request,
    std::function<void(Ice::OutgoingResponse)> sendResponse)
{
    checkNonIdempotent(request.current());
    auto istr = &request.inputStream();
    istr->startEncapsulation();
    std::string iceP_guid;
    std::string iceP_subinfo;
    ::Ice::Identity iceP_ident;
    istr->readAll(iceP_guid, iceP_subinfo, iceP_ident);
    istr->endEncapsulation();
    auto responseHandler = std::make_shared<IceInternal::AsyncResponseHandler>(std::move(sendResponse), request.current());
    auto responseCb = [responseHandler](std::string_view ret)
    {
        responseHandler->sendResponse(
            [&](Ice::OutputStream* ostr)
            {
                ostr->writeAll(ret);
            });
    };
    try
    {
        this->RegisterStockPushIO2Async(std::move(iceP_guid), std::move(iceP_subinfo), std::move(iceP_ident), std::move(responseCb), [responseHandler](std::exception_ptr ex) { responseHandler->sendException(ex); }, responseHandler->current());
    }
    catch (...)
    {
        responseHandler->sendException(std::current_exception());
    }
}

void
JSONBINRPC::AsyncIJsonBinRPC::_iceD_UnRegisterStockPushIO2(
    Ice::IncomingRequest& request,
    std::function<void(Ice::OutgoingResponse)> sendResponse)
{
    checkNonIdempotent(request.current());
    auto istr = &request.inputStream();
    istr->startEncapsulation();
    std::string iceP_guid;
    std::string iceP_subinfo;
    ::Ice::Identity iceP_ident;
    istr->readAll(iceP_guid, iceP_subinfo, iceP_ident);
    istr->endEncapsulation();
    auto responseHandler = std::make_shared<IceInternal::AsyncResponseHandler>(std::move(sendResponse), request.current());
    auto responseCb = [responseHandler](std::string_view ret)
    {
        responseHandler->sendResponse(
            [&](Ice::OutputStream* ostr)
            {
                ostr->writeAll(ret);
            });
    };
    try
    {
        this->UnRegisterStockPushIO2Async(std::move(iceP_guid), std::move(iceP_subinfo), std::move(iceP_ident), std::move(responseCb), [responseHandler](std::exception_ptr ex) { responseHandler->sendException(ex); }, responseHandler->current());
    }
    catch (...)
    {
        responseHandler->sendException(std::current_exception());
    }
}

const char*
JSONBINRPC::AsyncIJsonBinRPC::ice_staticId() noexcept
{
    return "::JSONBINRPC::IJsonBinRPC";
}
