// Copyright (c) ZeroC, Inc.

// slice2cpp version 3.8.2
// <auto-generated>Generated from Slice file 'JSONBINRPCU.ice'.</auto-generated>
// clang-format off

#ifndef JSONBINRPCU_h_
#define JSONBINRPCU_h_

#include <Ice/PushDisableWarnings.h>
#include <Ice/Ice.h>
#include <Ice/Identity.h>

#ifndef ICE_DISABLE_VERSION
#   if ICE_INT_VERSION / 100 != 308
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

// NOLINTBEGIN(modernize-concat-nested-namespaces)

namespace JSONBINRPC
{
    using AShort = std::vector<std::int16_t>;

    using AByte = std::vector<std::byte>;

    using AFloat = std::vector<float>;

    using AInt = std::vector<std::int32_t>;

    using AI64 = std::vector<std::int64_t>;

    /// @remarks The Slice compiler generated this enum class from Slice enumeration `::JSONBINRPC::BinaryCompression`.
    enum class BinaryCompression : std::uint8_t
    {
        BinaryCompressionNone,

        BinaryCompressionSnappy
    };

    /// Outputs the enumerator name or underlying value of a BinaryCompression to a stream.
    /// @param os The output stream.
    /// @param value The value to output.
    /// @return The output stream.
    std::ostream& operator<<(std::ostream& os, BinaryCompression value);

    struct BinaryPayload;

    struct BinaryRequest;

    struct BinaryResponse;

    class IJsonBinRPCPrx;
}

namespace JSONBINRPC
{
    /// @remarks The Slice compiler generated this proxy class from Slice interface `::JSONBINRPC::IJsonBinRPC`.
    class IJsonBinRPCPrx : public Ice::Proxy<IJsonBinRPCPrx, Ice::ObjectPrx>
    {
    public:
        /// Constructs a proxy from a Communicator and a proxy string.
        /// @param communicator The communicator of the new proxy.
        /// @param proxyString The proxy string to parse.
        IJsonBinRPCPrx(const Ice::CommunicatorPtr& communicator, std::string_view proxyString) : Ice::ObjectPrx{communicator, proxyString} {} // NOLINT(modernize-use-equals-default)

        /// Copy constructor. Constructs with a copy of the contents of @p other.
        /// @param other The proxy to copy from.
        IJsonBinRPCPrx(const IJsonBinRPCPrx& other) noexcept : Ice::ObjectPrx{other} {} // NOLINT(modernize-use-equals-default)

        /// Move constructor. Constructs a proxy with the contents of @p other using move semantics.
        /// @param other The proxy to move from.
        IJsonBinRPCPrx(IJsonBinRPCPrx&& other) noexcept : Ice::ObjectPrx{std::move(other)} {} // NOLINT(modernize-use-equals-default)

        ~IJsonBinRPCPrx() override;

        /// Copy assignment operator. Replaces the contents of this proxy with a copy of the contents of @p rhs.
        /// @param rhs The proxy to copy from.
        /// @return A reference to this proxy.
        IJsonBinRPCPrx& operator=(const IJsonBinRPCPrx& rhs) noexcept
        {
            if (this != &rhs)
            {
                Ice::ObjectPrx::operator=(rhs);
            }
            return *this;
        }

        /// Move assignment operator. Replaces the contents of this proxy with the contents of @p rhs using move semantics.
        /// @param rhs The proxy to move from.
        IJsonBinRPCPrx& operator=(IJsonBinRPCPrx&& rhs) noexcept
        {
            if (this != &rhs)
            {
                Ice::ObjectPrx::operator=(std::move(rhs));
            }
            return *this;
        }

        std::int64_t RegisterStockPushIO(std::string_view guid, const ::Ice::Identity& ident, const Ice::Context& context = Ice::noExplicitContext) const; // NOLINT(modernize-use-nodiscard)

        [[nodiscard]] std::future<std::int64_t> RegisterStockPushIOAsync(std::string_view guid, const ::Ice::Identity& ident, const Ice::Context& context = Ice::noExplicitContext) const;

        // NOLINTNEXTLINE(modernize-use-nodiscard)
        std::function<void()> RegisterStockPushIOAsync(std::string_view guid, const ::Ice::Identity& ident, std::function<void(std::int64_t)> response, std::function<void(std::exception_ptr)> exception = nullptr, std::function<void(bool)> sent = nullptr, const Ice::Context& context = Ice::noExplicitContext) const;

        /// @private
        void _iceI_RegisterStockPushIO(const std::shared_ptr<IceInternal::OutgoingAsyncT<std::int64_t>>&, std::string_view, const ::Ice::Identity&, const Ice::Context&) const;

        std::int64_t JsonBinRPC(std::int64_t syn, std::int64_t nFuncID, std::int64_t setcode, const AByte& reqJson, std::int64_t& ilparam, AByte& slparam, std::int64_t& iwparam, AByte& swparam, std::string& errinf, const Ice::Context& context = Ice::noExplicitContext) const;

        [[nodiscard]] std::future<std::tuple<std::int64_t, std::int64_t, AByte, std::int64_t, AByte, std::string>> JsonBinRPCAsync(std::int64_t syn, std::int64_t nFuncID, std::int64_t setcode, const AByte& reqJson, const Ice::Context& context = Ice::noExplicitContext) const;

        // NOLINTNEXTLINE(modernize-use-nodiscard)
        std::function<void()> JsonBinRPCAsync(std::int64_t syn, std::int64_t nFuncID, std::int64_t setcode, const AByte& reqJson, std::function<void(std::int64_t, std::int64_t, ::JSONBINRPC::AByte, std::int64_t, ::JSONBINRPC::AByte, std::string)> response, std::function<void(std::exception_ptr)> exception = nullptr, std::function<void(bool)> sent = nullptr, const Ice::Context& context = Ice::noExplicitContext) const;

        /// @private
        void _iceI_JsonBinRPC(const std::shared_ptr<IceInternal::OutgoingAsyncT<std::tuple<std::int64_t, std::int64_t, AByte, std::int64_t, AByte, std::string>>>&, std::int64_t, std::int64_t, std::int64_t, const AByte&, const Ice::Context&) const;

        std::int64_t JsonBinPUT(std::int64_t syn, std::int64_t nFuncID, std::int64_t setcode, const AByte& putJson, std::int64_t ilparam, const AByte& slparam, std::int64_t iwparam, const AByte& swparam, std::int64_t& oilparam, AByte& oslparam, std::int64_t& oiwparam, AByte& oswparam, std::string& errinf, const Ice::Context& context = Ice::noExplicitContext) const;

        [[nodiscard]] std::future<std::tuple<std::int64_t, std::int64_t, AByte, std::int64_t, AByte, std::string>> JsonBinPUTAsync(std::int64_t syn, std::int64_t nFuncID, std::int64_t setcode, const AByte& putJson, std::int64_t ilparam, const AByte& slparam, std::int64_t iwparam, const AByte& swparam, const Ice::Context& context = Ice::noExplicitContext) const;

        // NOLINTNEXTLINE(modernize-use-nodiscard)
        std::function<void()> JsonBinPUTAsync(std::int64_t syn, std::int64_t nFuncID, std::int64_t setcode, const AByte& putJson, std::int64_t ilparam, const AByte& slparam, std::int64_t iwparam, const AByte& swparam, std::function<void(std::int64_t, std::int64_t, ::JSONBINRPC::AByte, std::int64_t, ::JSONBINRPC::AByte, std::string)> response, std::function<void(std::exception_ptr)> exception = nullptr, std::function<void(bool)> sent = nullptr, const Ice::Context& context = Ice::noExplicitContext) const;

        /// @private
        void _iceI_JsonBinPUT(const std::shared_ptr<IceInternal::OutgoingAsyncT<std::tuple<std::int64_t, std::int64_t, AByte, std::int64_t, AByte, std::string>>>&, std::int64_t, std::int64_t, std::int64_t, const AByte&, std::int64_t, const AByte&, std::int64_t, const AByte&, const Ice::Context&) const;

        std::int64_t UnRegisterStockPushIO(std::string_view guid, const Ice::Context& context = Ice::noExplicitContext) const; // NOLINT(modernize-use-nodiscard)

        [[nodiscard]] std::future<std::int64_t> UnRegisterStockPushIOAsync(std::string_view guid, const Ice::Context& context = Ice::noExplicitContext) const;

        // NOLINTNEXTLINE(modernize-use-nodiscard)
        std::function<void()> UnRegisterStockPushIOAsync(std::string_view guid, std::function<void(std::int64_t)> response, std::function<void(std::exception_ptr)> exception = nullptr, std::function<void(bool)> sent = nullptr, const Ice::Context& context = Ice::noExplicitContext) const;

        /// @private
        void _iceI_UnRegisterStockPushIO(const std::shared_ptr<IceInternal::OutgoingAsyncT<std::int64_t>>&, std::string_view, const Ice::Context&) const;

        void ProcessPackage(std::int64_t reqno, const BinaryPayload& payload, const Ice::Context& context = Ice::noExplicitContext) const;

        [[nodiscard]] std::future<void> ProcessPackageAsync(std::int64_t reqno, const BinaryPayload& payload, const Ice::Context& context = Ice::noExplicitContext) const;

        // NOLINTNEXTLINE(modernize-use-nodiscard)
        std::function<void()> ProcessPackageAsync(std::int64_t reqno, const BinaryPayload& payload, std::function<void()> response, std::function<void(std::exception_ptr)> exception = nullptr, std::function<void(bool)> sent = nullptr, const Ice::Context& context = Ice::noExplicitContext) const;

        /// @private
        void _iceI_ProcessPackage(const std::shared_ptr<IceInternal::OutgoingAsyncT<void>>&, std::int64_t, const BinaryPayload&, const Ice::Context&) const;

        std::string RegisterStockPushIO2(std::string_view guid, std::string_view subinfo, const ::Ice::Identity& ident, const Ice::Context& context = Ice::noExplicitContext) const; // NOLINT(modernize-use-nodiscard)

        [[nodiscard]] std::future<std::string> RegisterStockPushIO2Async(std::string_view guid, std::string_view subinfo, const ::Ice::Identity& ident, const Ice::Context& context = Ice::noExplicitContext) const;

        // NOLINTNEXTLINE(modernize-use-nodiscard)
        std::function<void()> RegisterStockPushIO2Async(std::string_view guid, std::string_view subinfo, const ::Ice::Identity& ident, std::function<void(std::string)> response, std::function<void(std::exception_ptr)> exception = nullptr, std::function<void(bool)> sent = nullptr, const Ice::Context& context = Ice::noExplicitContext) const;

        /// @private
        void _iceI_RegisterStockPushIO2(const std::shared_ptr<IceInternal::OutgoingAsyncT<std::string>>&, std::string_view, std::string_view, const ::Ice::Identity&, const Ice::Context&) const;

        std::string UnRegisterStockPushIO2(std::string_view guid, std::string_view subinfo, const ::Ice::Identity& ident, const Ice::Context& context = Ice::noExplicitContext) const; // NOLINT(modernize-use-nodiscard)

        [[nodiscard]] std::future<std::string> UnRegisterStockPushIO2Async(std::string_view guid, std::string_view subinfo, const ::Ice::Identity& ident, const Ice::Context& context = Ice::noExplicitContext) const;

        // NOLINTNEXTLINE(modernize-use-nodiscard)
        std::function<void()> UnRegisterStockPushIO2Async(std::string_view guid, std::string_view subinfo, const ::Ice::Identity& ident, std::function<void(std::string)> response, std::function<void(std::exception_ptr)> exception = nullptr, std::function<void(bool)> sent = nullptr, const Ice::Context& context = Ice::noExplicitContext) const;

        /// @private
        void _iceI_UnRegisterStockPushIO2(const std::shared_ptr<IceInternal::OutgoingAsyncT<std::string>>&, std::string_view, std::string_view, const ::Ice::Identity&, const Ice::Context&) const;

        BinaryResponse BinaryRPC(const BinaryRequest& req, const Ice::Context& context = Ice::noExplicitContext) const; // NOLINT(modernize-use-nodiscard)

        [[nodiscard]] std::future<BinaryResponse> BinaryRPCAsync(const BinaryRequest& req, const Ice::Context& context = Ice::noExplicitContext) const;

        // NOLINTNEXTLINE(modernize-use-nodiscard)
        std::function<void()> BinaryRPCAsync(const BinaryRequest& req, std::function<void(::JSONBINRPC::BinaryResponse)> response, std::function<void(std::exception_ptr)> exception = nullptr, std::function<void(bool)> sent = nullptr, const Ice::Context& context = Ice::noExplicitContext) const;

        /// @private
        void _iceI_BinaryRPC(const std::shared_ptr<IceInternal::OutgoingAsyncT<BinaryResponse>>&, const BinaryRequest&, const Ice::Context&) const;

        BinaryResponse BinaryPUT(const BinaryRequest& req, const Ice::Context& context = Ice::noExplicitContext) const; // NOLINT(modernize-use-nodiscard)

        [[nodiscard]] std::future<BinaryResponse> BinaryPUTAsync(const BinaryRequest& req, const Ice::Context& context = Ice::noExplicitContext) const;

        // NOLINTNEXTLINE(modernize-use-nodiscard)
        std::function<void()> BinaryPUTAsync(const BinaryRequest& req, std::function<void(::JSONBINRPC::BinaryResponse)> response, std::function<void(std::exception_ptr)> exception = nullptr, std::function<void(bool)> sent = nullptr, const Ice::Context& context = Ice::noExplicitContext) const;

        /// @private
        void _iceI_BinaryPUT(const std::shared_ptr<IceInternal::OutgoingAsyncT<BinaryResponse>>&, const BinaryRequest&, const Ice::Context&) const;

        /// Gets the type ID of the associated Slice interface.
        /// @return The string `"::JSONBINRPC::IJsonBinRPC"`.
        static const char* ice_staticId() noexcept;

        /// @private
        static IJsonBinRPCPrx _fromReference(IceInternal::ReferencePtr ref) { return IJsonBinRPCPrx{std::move(ref)}; }

    protected:
        /// @private
        IJsonBinRPCPrx() = default;

        /// @private
        explicit IJsonBinRPCPrx(IceInternal::ReferencePtr&& ref) : Ice::ObjectPrx{std::move(ref)}
        {
        }
    };
}

namespace JSONBINRPC
{
    /// @remarks The Slice compiler generated this struct from Slice struct `::JSONBINRPC::BinaryPayload`.
    struct BinaryPayload
    {
        std::int32_t version;

        ::JSONBINRPC::BinaryCompression compression;

        std::int32_t rawSize;

        ::JSONBINRPC::AByte data;

        /// Creates a tuple with all the fields of this struct.
        /// @return A tuple with all the fields of this struct.
        [[nodiscard]] std::tuple<const std::int32_t&, const ::JSONBINRPC::BinaryCompression&, const std::int32_t&, const ::JSONBINRPC::AByte&> ice_tuple() const
        {
            return std::tie(version, compression, rawSize, data);
        }

        /// Outputs the name and value of each field of this instance to the stream.
        /// @param os The output stream.
        void ice_printFields(std::ostream& os) const;
    };

    /// Outputs the description of a BinaryPayload to a stream, including all its fields.
    /// @param os The output stream.
    /// @param value The instance to output.
    /// @return The output stream.
    std::ostream& operator<<(std::ostream& os, const BinaryPayload& value);

    /// @remarks The Slice compiler generated this struct from Slice struct `::JSONBINRPC::BinaryRequest`.
    struct BinaryRequest
    {
        std::int32_t version;

        std::int64_t syn;

        std::int64_t nFuncID;

        std::int64_t routeCode;

        std::int64_t param;

        ::JSONBINRPC::BinaryPayload payload;

        std::int64_t wparam;

        ::JSONBINRPC::BinaryPayload extra;

        /// Creates a tuple with all the fields of this struct.
        /// @return A tuple with all the fields of this struct.
        [[nodiscard]] std::tuple<const std::int32_t&, const std::int64_t&, const std::int64_t&, const std::int64_t&, const std::int64_t&, const ::JSONBINRPC::BinaryPayload&, const std::int64_t&, const ::JSONBINRPC::BinaryPayload&> ice_tuple() const
        {
            return std::tie(version, syn, nFuncID, routeCode, param, payload, wparam, extra);
        }

        /// Outputs the name and value of each field of this instance to the stream.
        /// @param os The output stream.
        void ice_printFields(std::ostream& os) const;
    };

    /// Outputs the description of a BinaryRequest to a stream, including all its fields.
    /// @param os The output stream.
    /// @param value The instance to output.
    /// @return The output stream.
    std::ostream& operator<<(std::ostream& os, const BinaryRequest& value);

    /// @remarks The Slice compiler generated this struct from Slice struct `::JSONBINRPC::BinaryResponse`.
    struct BinaryResponse
    {
        std::int32_t version;

        std::int64_t retVal;

        std::int32_t errorCode;

        std::int64_t param;

        ::JSONBINRPC::BinaryPayload payload;

        std::int64_t wparam;

        ::JSONBINRPC::BinaryPayload extra;

        std::string errInfo;

        /// Creates a tuple with all the fields of this struct.
        /// @return A tuple with all the fields of this struct.
        [[nodiscard]] std::tuple<const std::int32_t&, const std::int64_t&, const std::int32_t&, const std::int64_t&, const ::JSONBINRPC::BinaryPayload&, const std::int64_t&, const ::JSONBINRPC::BinaryPayload&, const std::string&> ice_tuple() const
        {
            return std::tie(version, retVal, errorCode, param, payload, wparam, extra, errInfo);
        }

        /// Outputs the name and value of each field of this instance to the stream.
        /// @param os The output stream.
        void ice_printFields(std::ostream& os) const;
    };

    /// Outputs the description of a BinaryResponse to a stream, including all its fields.
    /// @param os The output stream.
    /// @param value The instance to output.
    /// @return The output stream.
    std::ostream& operator<<(std::ostream& os, const BinaryResponse& value);

    /// @cond INTERNAL
    using Ice::Tuple::operator<;
    using Ice::Tuple::operator<=;
    using Ice::Tuple::operator>;
    using Ice::Tuple::operator>=;
    using Ice::Tuple::operator==;
    using Ice::Tuple::operator!=;
    /// @endcond
}

namespace JSONBINRPC
{
    /// @remarks The Slice compiler generated this skeleton class from Slice interface `::JSONBINRPC::IJsonBinRPC`.
    class IJsonBinRPC : public virtual Ice::Object
    {
    public:
        /// The associated proxy type.
        using ProxyType = IJsonBinRPCPrx;

        /// Dispatches an incoming request to one of the member functions of this generated class, based on the operation name carried by the request.
        /// @param request The incoming request.
        /// @param sendResponse The callback to send the response.
        void dispatch(Ice::IncomingRequest& request, std::function<void(Ice::OutgoingResponse)> sendResponse) override;

        [[nodiscard]] std::vector<std::string> ice_ids(const Ice::Current& current) const override;

        [[nodiscard]] std::string ice_id(const Ice::Current& current) const override;

        virtual void RegisterStockPushIOAsync(std::string guid, ::Ice::Identity ident, std::function<void(std::int64_t returnValue)> response, std::function<void(std::exception_ptr)> exception, const Ice::Current& current) = 0;

        /// @private
        void _iceD_RegisterStockPushIO(Ice::IncomingRequest&, std::function<void(Ice::OutgoingResponse)>);

        virtual void JsonBinRPCAsync(std::int64_t syn, std::int64_t nFuncID, std::int64_t setcode, AByte reqJson, std::function<void(std::int64_t returnValue, std::int64_t ilparam, const AByte& slparam, std::int64_t iwparam, const AByte& swparam, std::string_view errinf)> response, std::function<void(std::exception_ptr)> exception, const Ice::Current& current) = 0;

        /// @private
        void _iceD_JsonBinRPC(Ice::IncomingRequest&, std::function<void(Ice::OutgoingResponse)>);

        virtual void JsonBinPUTAsync(std::int64_t syn, std::int64_t nFuncID, std::int64_t setcode, AByte putJson, std::int64_t ilparam, AByte slparam, std::int64_t iwparam, AByte swparam, std::function<void(std::int64_t returnValue, std::int64_t oilparam, const AByte& oslparam, std::int64_t oiwparam, const AByte& oswparam, std::string_view errinf)> response, std::function<void(std::exception_ptr)> exception, const Ice::Current& current) = 0;

        /// @private
        void _iceD_JsonBinPUT(Ice::IncomingRequest&, std::function<void(Ice::OutgoingResponse)>);

        virtual void UnRegisterStockPushIOAsync(std::string guid, std::function<void(std::int64_t returnValue)> response, std::function<void(std::exception_ptr)> exception, const Ice::Current& current) = 0;

        /// @private
        void _iceD_UnRegisterStockPushIO(Ice::IncomingRequest&, std::function<void(Ice::OutgoingResponse)>);

        virtual void ProcessPackageAsync(std::int64_t reqno, BinaryPayload payload, std::function<void()> response, std::function<void(std::exception_ptr)> exception, const Ice::Current& current) = 0;

        /// @private
        void _iceD_ProcessPackage(Ice::IncomingRequest&, std::function<void(Ice::OutgoingResponse)>);

        virtual void RegisterStockPushIO2Async(std::string guid, std::string subinfo, ::Ice::Identity ident, std::function<void(std::string_view returnValue)> response, std::function<void(std::exception_ptr)> exception, const Ice::Current& current) = 0;

        /// @private
        void _iceD_RegisterStockPushIO2(Ice::IncomingRequest&, std::function<void(Ice::OutgoingResponse)>);

        virtual void UnRegisterStockPushIO2Async(std::string guid, std::string subinfo, ::Ice::Identity ident, std::function<void(std::string_view returnValue)> response, std::function<void(std::exception_ptr)> exception, const Ice::Current& current) = 0;

        /// @private
        void _iceD_UnRegisterStockPushIO2(Ice::IncomingRequest&, std::function<void(Ice::OutgoingResponse)>);

        virtual void BinaryRPCAsync(BinaryRequest req, std::function<void(const BinaryResponse& returnValue)> response, std::function<void(std::exception_ptr)> exception, const Ice::Current& current) = 0;

        /// @private
        void _iceD_BinaryRPC(Ice::IncomingRequest&, std::function<void(Ice::OutgoingResponse)>);

        virtual void BinaryPUTAsync(BinaryRequest req, std::function<void(const BinaryResponse& returnValue)> response, std::function<void(std::exception_ptr)> exception, const Ice::Current& current) = 0;

        /// @private
        void _iceD_BinaryPUT(Ice::IncomingRequest&, std::function<void(Ice::OutgoingResponse)>);

        /// Gets the type ID of the associated Slice interface.
        /// @return The string `"::JSONBINRPC::IJsonBinRPC"`.
        static const char* ice_staticId() noexcept;
    };

    /// A shared pointer to an IJsonBinRPC.
    using IJsonBinRPCPtr = std::shared_ptr<IJsonBinRPC>;
}

namespace JSONBINRPC
{
    /// @remarks The Slice compiler generated this skeleton class from Slice interface `::JSONBINRPC::IJsonBinRPC`.
    class AsyncIJsonBinRPC : public virtual Ice::Object
    {
    public:
        /// The associated proxy type.
        using ProxyType = IJsonBinRPCPrx;

        /// Dispatches an incoming request to one of the member functions of this generated class, based on the operation name carried by the request.
        /// @param request The incoming request.
        /// @param sendResponse The callback to send the response.
        void dispatch(Ice::IncomingRequest& request, std::function<void(Ice::OutgoingResponse)> sendResponse) override;

        [[nodiscard]] std::vector<std::string> ice_ids(const Ice::Current& current) const override;

        [[nodiscard]] std::string ice_id(const Ice::Current& current) const override;

        virtual void RegisterStockPushIOAsync(std::string guid, ::Ice::Identity ident, std::function<void(std::int64_t returnValue)> response, std::function<void(std::exception_ptr)> exception, const Ice::Current& current) = 0;

        /// @private
        void _iceD_RegisterStockPushIO(Ice::IncomingRequest&, std::function<void(Ice::OutgoingResponse)>);

        virtual void JsonBinRPCAsync(std::int64_t syn, std::int64_t nFuncID, std::int64_t setcode, AByte reqJson, std::function<void(std::int64_t returnValue, std::int64_t ilparam, const AByte& slparam, std::int64_t iwparam, const AByte& swparam, std::string_view errinf)> response, std::function<void(std::exception_ptr)> exception, const Ice::Current& current) = 0;

        /// @private
        void _iceD_JsonBinRPC(Ice::IncomingRequest&, std::function<void(Ice::OutgoingResponse)>);

        virtual void JsonBinPUTAsync(std::int64_t syn, std::int64_t nFuncID, std::int64_t setcode, AByte putJson, std::int64_t ilparam, AByte slparam, std::int64_t iwparam, AByte swparam, std::function<void(std::int64_t returnValue, std::int64_t oilparam, const AByte& oslparam, std::int64_t oiwparam, const AByte& oswparam, std::string_view errinf)> response, std::function<void(std::exception_ptr)> exception, const Ice::Current& current) = 0;

        /// @private
        void _iceD_JsonBinPUT(Ice::IncomingRequest&, std::function<void(Ice::OutgoingResponse)>);

        virtual void UnRegisterStockPushIOAsync(std::string guid, std::function<void(std::int64_t returnValue)> response, std::function<void(std::exception_ptr)> exception, const Ice::Current& current) = 0;

        /// @private
        void _iceD_UnRegisterStockPushIO(Ice::IncomingRequest&, std::function<void(Ice::OutgoingResponse)>);

        virtual void ProcessPackageAsync(std::int64_t reqno, BinaryPayload payload, std::function<void()> response, std::function<void(std::exception_ptr)> exception, const Ice::Current& current) = 0;

        /// @private
        void _iceD_ProcessPackage(Ice::IncomingRequest&, std::function<void(Ice::OutgoingResponse)>);

        virtual void RegisterStockPushIO2Async(std::string guid, std::string subinfo, ::Ice::Identity ident, std::function<void(std::string_view returnValue)> response, std::function<void(std::exception_ptr)> exception, const Ice::Current& current) = 0;

        /// @private
        void _iceD_RegisterStockPushIO2(Ice::IncomingRequest&, std::function<void(Ice::OutgoingResponse)>);

        virtual void UnRegisterStockPushIO2Async(std::string guid, std::string subinfo, ::Ice::Identity ident, std::function<void(std::string_view returnValue)> response, std::function<void(std::exception_ptr)> exception, const Ice::Current& current) = 0;

        /// @private
        void _iceD_UnRegisterStockPushIO2(Ice::IncomingRequest&, std::function<void(Ice::OutgoingResponse)>);

        virtual void BinaryRPCAsync(BinaryRequest req, std::function<void(const BinaryResponse& returnValue)> response, std::function<void(std::exception_ptr)> exception, const Ice::Current& current) = 0;

        /// @private
        void _iceD_BinaryRPC(Ice::IncomingRequest&, std::function<void(Ice::OutgoingResponse)>);

        virtual void BinaryPUTAsync(BinaryRequest req, std::function<void(const BinaryResponse& returnValue)> response, std::function<void(std::exception_ptr)> exception, const Ice::Current& current) = 0;

        /// @private
        void _iceD_BinaryPUT(Ice::IncomingRequest&, std::function<void(Ice::OutgoingResponse)>);

        /// Gets the type ID of the associated Slice interface.
        /// @return The string `"::JSONBINRPC::IJsonBinRPC"`.
        static const char* ice_staticId() noexcept;
    };

    /// A shared pointer to an AsyncIJsonBinRPC.
    using AsyncIJsonBinRPCPtr = std::shared_ptr<AsyncIJsonBinRPC>;
}

namespace Ice
{
    /// @cond INTERNAL
    template<>
    struct StreamableTraits<::JSONBINRPC::BinaryCompression>
    {
        static constexpr StreamHelperCategory helper = StreamHelperCategoryEnum;
        static constexpr int minValue = 0;
        static constexpr int maxValue = 1;
        static constexpr int minWireSize = 1;
        static constexpr bool fixedLength = false;
    };
    /// @endcond

    /// @cond INTERNAL
    template<>
    struct StreamableTraits<::JSONBINRPC::BinaryPayload>
    {
        static constexpr StreamHelperCategory helper = StreamHelperCategoryStruct;
        static constexpr int minWireSize = 10;
        static constexpr bool fixedLength = false;
    };

    template<>
    struct StreamReader<::JSONBINRPC::BinaryPayload>
    {
        /// Unmarshals a ::JSONBINRPC::BinaryPayload from the input stream.
        static void read(InputStream* istr, ::JSONBINRPC::BinaryPayload& v)
        {
            istr->readAll(v.version, v.compression, v.rawSize, v.data);
        }
    };
    /// @endcond

    /// @cond INTERNAL
    template<>
    struct StreamableTraits<::JSONBINRPC::BinaryRequest>
    {
        static constexpr StreamHelperCategory helper = StreamHelperCategoryStruct;
        static constexpr int minWireSize = 64;
        static constexpr bool fixedLength = false;
    };

    template<>
    struct StreamReader<::JSONBINRPC::BinaryRequest>
    {
        /// Unmarshals a ::JSONBINRPC::BinaryRequest from the input stream.
        static void read(InputStream* istr, ::JSONBINRPC::BinaryRequest& v)
        {
            istr->readAll(v.version, v.syn, v.nFuncID, v.routeCode, v.param, v.payload, v.wparam, v.extra);
        }
    };
    /// @endcond

    /// @cond INTERNAL
    template<>
    struct StreamableTraits<::JSONBINRPC::BinaryResponse>
    {
        static constexpr StreamHelperCategory helper = StreamHelperCategoryStruct;
        static constexpr int minWireSize = 53;
        static constexpr bool fixedLength = false;
    };

    template<>
    struct StreamReader<::JSONBINRPC::BinaryResponse>
    {
        /// Unmarshals a ::JSONBINRPC::BinaryResponse from the input stream.
        static void read(InputStream* istr, ::JSONBINRPC::BinaryResponse& v)
        {
            istr->readAll(v.version, v.retVal, v.errorCode, v.param, v.payload, v.wparam, v.extra, v.errInfo);
        }
    };
    /// @endcond
}

// NOLINTEND(modernize-concat-nested-namespaces)

#include <Ice/PopDisableWarnings.h>
#endif
